name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug:
        description: 'Whether to build in debug mode'
        required: false
        default: 'false'
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  build:
    name: Build Web Site
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Soluna
        uses: ./.github/actions/soluna
        id: build
        with:
          soluna_path: "."
          debug: ${{ github.event.inputs.debug || 'false' }}

      - name: Build Sample
        uses: ./.github/actions/sample
        id: sample
        with:
          soluna_path: "."

      - name: Build Astro
        uses: withastro/action@v6
        env:
          SITE_BASE: /soluna/
          SOLUNA_JS_PATH: ${{ steps.build.outputs.SOLUNA_JS_PATH }}
          SOLUNA_WASM_PATH: ${{ steps.build.outputs.SOLUNA_WASM_PATH }}
          SOLUNA_WASM_MAP_PATH: ${{ steps.build.outputs.SOLUNA_WASM_MAP_PATH }}
          SAMPLE_WASM_PATH: ${{ steps.sample.outputs.SAMPLE_WASM_PATH }}
        with:
          path: website
          node-version: 24
          package-manager: pnpm@10.28.2
          build-cmd: pnpm run build
          out-dir: dist

  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.actor != 'nektos/act'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
